sudo: required

os:
  - linux
  - osx

language: go
go:
  - 1.9.x

install:
  - make deps

script:
  - go get github.com/libp2p/go-reuseport
  - bash ./run-standard-tests.sh

cache:
  directories:
    - $GOPATH/src/gx

notifications:
  email: false

env: GOTFLAGS="-race -cpu=5"
